import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { OfficerShell, OfficerStepper } from "@/components/officer/OfficerShell";
import { AIDraftPanel } from "@/components/officer/AIDraftPanel";
import { SaveDraftButton } from "@/components/officer/SaveDraftButton";
import { aiDraftSteps, intakeForm } from "@/data/officer";

const intakeFields = [
  { label: "Youth name", value: intakeForm.name },
  { label: "Goal", value: intakeForm.goal },
  { label: "Skills / background", value: intakeForm.skills },
  { label: "Current situation / notes", value: intakeForm.situation, textarea: true },
  { label: "Location", value: intakeForm.location },
];

export default function OfficerIntake() {
  return (
    <OfficerShell active="Smart Intake">
      <div className="officer-page-wrap">
        <header className="officer-heading">
          <div>
            <h1>Smart Intake</h1>
            <p>
              Enter what you know about the youth. AI will draft a roadmap you
              can review and edit.
            </p>
          </div>
          <SaveDraftButton />
        </header>

        <OfficerStepper
          steps={["Intake Notes", "AI Draft", "Review & Edit", "Approve"]}
          current={1}
        />

        <div className="intake-grid">
          <section className="officer-card intake-notes">
            <header className="officer-card-header">
              <div>
                <h2>Intake Notes</h2>
                <p>What you know about this youth</p>
              </div>
            </header>
            <div className="intake-fields">
              {intakeFields.map((field) => (
                <label className="intake-field" key={field.label}>
                  <span>{field.label}</span>
                  {field.textarea ? (
                    <textarea rows={3} defaultValue={field.value} />
                  ) : (
                    <input type="text" defaultValue={field.value} />
                  )}
                </label>
              ))}
            </div>
          </section>

          <AIDraftPanel steps={aiDraftSteps} />
        </div>

        <footer className="intake-footer">
          <p className="draft-note">
            This is a draft generated by AI. Review carefully before approving.
          </p>
          <Link className="officer-button primary" href="/officer/intake/review">
            Review &amp; edit
            <ArrowRight aria-hidden size={15} />
          </Link>
        </footer>
      </div>
    </OfficerShell>
  );
}
