import Link from "next/link";
import { ArrowLeft, ShieldAlert } from "lucide-react";
import { OfficerShell, OfficerStepper } from "@/components/officer/OfficerShell";
import { ReviewActions } from "@/components/officer/ReviewActions";
import { youthDetail } from "@/data/officer";

const reviewRows = [
  { label: "Goal", value: youthDetail.goal },
  { label: "Youth", value: youthDetail.name },
  { label: "Location", value: youthDetail.location },
  { label: "Steps in plan", value: String(youthDetail.progress.total) },
];

export default function OfficerReview() {
  return (
    <OfficerShell active="Smart Intake">
      <div className="officer-page-wrap">
        <Link className="officer-back-link" href="/officer/intake">
          <ArrowLeft aria-hidden size={15} />
          Back to intake
        </Link>

        <header className="officer-heading">
          <div>
            <h1>Review &amp; Approve Roadmap</h1>
            <p>You are the final decision-maker.</p>
          </div>
        </header>

        <OfficerStepper
          steps={["Intake Notes", "AI Draft", "Review & Edit", "Approve"]}
          current={3}
        />

        <aside className="officer-warning">
          <span className="officer-warning-icon">
            <ShieldAlert aria-hidden size={22} />
          </span>
          <div>
            <strong>This roadmap is a DRAFT.</strong>
            <p>
              It is generated by AI from verified sources and must be reviewed
              by you. Only after you approve will the youth see it.
            </p>
          </div>
        </aside>

        <div className="review-columns">
          <section className="officer-card review-summary">
            <header className="officer-card-header">
              <div>
                <h2>Review summary</h2>
                <p>Key details of this roadmap</p>
              </div>
            </header>
            <dl className="review-rows">
              {reviewRows.map((row) => (
                <div key={row.label}>
                  <dt>{row.label}</dt>
                  <dd>{row.value}</dd>
                </div>
              ))}
            </dl>
            <div className="review-steps">
              <strong>Plan preview</strong>
              <ol>
                {youthDetail.roadmap.map((step) => (
                  <li key={step.number}>
                    <span>{step.number}</span>
                    {step.title}
                  </li>
                ))}
              </ol>
            </div>
          </section>

          <section className="officer-card review-approval">
            <header className="officer-card-header">
              <div>
                <h2>Your approval</h2>
                <p>Confirm before sending to the youth</p>
              </div>
            </header>
            <label className="intake-field">
              <span>Add a note for the youth (optional)</span>
              <textarea
                rows={5}
                placeholder="Write a message or guidance for the youth..."
              />
            </label>
          </section>
        </div>

        <ReviewActions />
        <p className="review-note">
          By approving, you confirm this roadmap is accurate to the best of your
          knowledge.
        </p>
      </div>
    </OfficerShell>
  );
}
